export ZSH="/home/kamrul-hasan/.oh-my-zsh"
ZSH_THEME="modified"
plugins=(git vi-mode z zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh
if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 else
   export EDITOR='mvim'
fi

# Start Tmux 
#tmux attach &> /dev/null    #Always Single Session
#if [[ ! $TERM =~ screen ]]; then
#      exec tmux
#fi


# Run as Vi
export VISUAL=vim
export EDITOR="$VISUAL"

# Debugging with ipython
export PYTHONBREAKPOINT=ipdb.set_trace

# Alias for xclip
alias xclip='clip.exe' # For WSL
# alias xclip='xclip -selection clipboard' # For Linux

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Extra
alias starwar='telnet towel.blinkenlights.nl'
alias matrix='cmatrix'

# FZF Settings
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND="rg --files --follow --glob '!.git'"
export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --border"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

#cargo
export PATH=/home/kamrul-hasan/.cargo/bin/:$PATH

# Ruby Settings
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# Alias for xclip
# alias xclip='clip.exe' # For WSL
alias xclip='xclip -selection clipboard' # For Linux

#cargo
export PATH=/home/kamrul/.cargo/bin/:$PATH

#
# hxwls <Series Folder With Multiple Link> | rg ".<Extension>$" | xargs wget
#
alias yt-v="youtube-dl -f best -o '%(title)s.%(ext)s'"
alias yt-pl="youtube-dl -o '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s'"
alias wget-inf="wget -c --retry-connrefused --tries=0"

# Swap Caps-lock and ESC key
setxkbmap -option caps:swapescape
