export ZSH="/home/kamrul-hasan/.oh-my-zsh"
ZSH_THEME="modified"
#ZSH_THEME="eastwood"
plugins=(git vi-mode z zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh
if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 else
   export EDITOR='mvim'
fi

# Start Tmux 
#tmux attach &> /dev/null    #Always Single Session
#if [[ ! $TERM =~ screen ]]; then
#      exec tmux
#fi


# Run as Vi
export VISUAL=vim
export EDITOR="$VISUAL"

# Debugging with ipython
export PYTHONBREAKPOINT=ipdb.set_trace

# Alias for xclip
alias xclip='clip.exe' # For WSL
# alias xclip='xclip -selection clipboard' # For Linux

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Extra
alias starwar='telnet towel.blinkenlights.nl'
alias matrix='cmatrix'

# FZF Settings
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND="rg --files --follow --glob '!.git'"
export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --border"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

#cargo
export PATH=/home/kamrul-hasan/.cargo/bin/:$PATH

# Ruby Settings
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# Alias for xclip
# alias xclip='clip.exe' # For WSL
alias xclip='xclip -selection clipboard' # For Linux

#cargo
export PATH=/home/kamrul/.cargo/bin/:$PATH

#
# hxwls <Series Folder With Multiple Link> | rg ".<Extension>$" | xargs wget
#
alias yt-v="yt-dlp -f best -o '%(title)s.%(ext)s'"
alias yt-pl="yt-dlp -o '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s'"
alias aria2c="aria2c -c -s 16 -x 16 -j 1 -k 1M"
alias wget-inf="wget -c --retry-connrefused --tries=0"

# Swap Caps-lock and ESC key
setxkbmap -option caps:swapescape

# Show Cost
alias show_cost="cat ~/Coding_Project/Daily_Cost/cost.csv | column -t -s,"
alias add_cost="python ~/Coding_Project/Daily_Cost/cost.py"
alias change_cost="vim ~/Coding_Project/Daily_Cost/cost.csv"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/kamrul-hasan/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/kamrul-hasan/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/kamrul-hasan/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/kamrul-hasan/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

set_brightness() {
  # 0(black) - 937(hight argument possible)
  # (high-low)/100 * my_percent = my_percent between hight & low
  # +1 is to ensure never going totally black
  # ${1#-} = absolute value of the input
  echo $(((${1#-}*(937-1)/100)+1)) | sudo tee /sys/class/backlight/intel_backlight/brightness 1> /dev/null
}

alias brightness_lowest="echo 1 | sudo tee /sys/class/backlight/intel_backlight/brightness 1> /dev/null"
alias brightness_normal="echo 235 | sudo tee /sys/class/backlight/intel_backlight/brightness 1> /dev/null"
alias min_music="cvlc --novideo" 

alias yt_v="yt-dlp -o '%(title)s.%(ext)s'"
alias yt_pl="yt-dlp -o '%(playlist)s/%(title)s.%(ext)s'"
alias anki_pic=$HOME/.local/share/Anki2/

export NVM_DIR="/home/kamrul-hasan/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
