#!/bin/bash
###########################################
# In contest, we are required to write, compile , run the code and pass the given test cases.
# This code will automate the whole process and requires only one inital setup.
# Run the file like:
#                   python3 test.py < EOD
#                   X
#                   Y
#                   Z
#                   EOD
#
# Like this X Y Z can be counted as vaild input for test.py file
# If inital output matches the given output, in terminal "Test-Case 1 Passed" will be shown
